Repository Princeton21/Data-Structures-and-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#395 Added linear search in Golang
  Code/search_algorithms/linear_search/README.md
  Code/search_algorithms/linear_search/linear_search.go
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#394 Added Manacher's Algorithm
  Code/string_algorithms/Manacher's Algorithm/Manacher'sAlgorithm.cpp
  Code/string_algorithms/Manacher's Algorithm/README.md
  Code/string_algorithms/README.md
Labels: hacktoberfest, hacktoberfest-accepted, new-algorithm

#405 Code to check a binary tree is balanced or not
  Code/data_structures/tree/binary_tree/balancedtree.cpp
Labels: hacktoberfest-accepted

#408 ALL Binary Tree Code Using CPP
  Code/binarytree_CPP/BT to LL using stack.cpp
  Code/binarytree_CPP/Sum & No of roots.cpp
  Code/binarytree_CPP/balanced tree.cpp
  Code/binarytree_CPP/bottom view.cpp
  Code/binarytree_CPP/boundary traversal.cpp
  Code/binarytree_CPP/bt from string bracket .cpp
  Code/binarytree_CPP/create binary tree.cpp
  Code/binarytree_CPP/diagonal traversal.cpp
  Code/binarytree_CPP/diameter and height of tree.cpp
  Code/binarytree_CPP/get duplicate trees.cpp
  Code/binarytree_CPP/inorder preorder postorder iterative.cpp
  Code/binarytree_CPP/k sum paths.cpp
  Code/binarytree_CPP/lca and shortest distance.cpp
  Code/binarytree_CPP/level order traversal.cpp
  Code/binarytree_CPP/max sum path.cpp
  Code/binarytree_CPP/minimum swaps bt to bst.cpp
  Code/binarytree_CPP/mirror of tree.cpp
  Code/binarytree_CPP/preorder inorder postorder.cpp
  Code/binarytree_CPP/right view left view.cpp
  Code/binarytree_CPP/roots at k distance.cpp
  Code/binarytree_CPP/sum of nodes at k level.cpp
  Code/binarytree_CPP/sum of nodes on longest path from root to leaf.cpp
  Code/binarytree_CPP/sum replacement.cpp
  Code/binarytree_CPP/sum tree check & leaf node at same level.cpp
  Code/binarytree_CPP/topView.cpp
  Code/binarytree_CPP/tree from postorder inorder.cpp
  Code/binarytree_CPP/tree from preorder inorder.cpp
  Code/binarytree_CPP/zigzag traversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#410 Added Rod cutting problem in DP
  Code/dynamic_programming_algorithms/Rod_Cutting.cpp
Labels: hacktoberfest, hacktoberfest-accepted
